// src/constants/masterTags.ts
export type MasterTag = {
  code: string;
  name: string;
  color: string;
  category: string;
};

export const DEFAULT_MASTER_TAGS: MasterTag[] = [
  // --------------------------- LIGHTS (interior/exterior) ---------------------------
  { code: "A", name: "Lights A", color: "#F97316", category: "Lights" },
  { code: "A1", name: "Lights A1 (Night Light)", color: "#F97316", category: "Lights" },
  { code: "B", name: "Lights B", color: "#F97316", category: "Lights" },
  { code: "C", name: "Lights C", color: "#F97316", category: "Lights" },
  { code: "D", name: "Lights D", color: "#F97316", category: "Lights" },
  { code: "E", name: "Lights E", color: "#F97316", category: "Lights" },
  { code: "F", name: "Lights F", color: "#F97316", category: "Lights" },
  { code: "G", name: "Lights G", color: "#F97316", category: "Lights" },
  { code: "H", name: "Lights H", color: "#F97316", category: "Lights" },
  { code: "I", name: "Lights I", color: "#F97316", category: "Lights" },
  { code: "J", name: "Lights J", color: "#F97316", category: "Lights" },
  { code: "K", name: "Lights K", color: "#F97316", category: "Lights" },
  { code: "L", name: "Lights L", color: "#F97316", category: "Lights" },
  { code: "M", name: "Lights M", color: "#F97316", category: "Lights" },
  { code: "N", name: "Lights N", color: "#F97316", category: "Lights" },
  { code: "O", name: "Lights O", color: "#F97316", category: "Lights" },
  { code: "P", name: "Lights P", color: "#F97316", category: "Lights" },
  { code: "Q", name: "Lights Q", color: "#F97316", category: "Lights" },
  { code: "R", name: "Lights R", color: "#F97316", category: "Lights" },
  { code: "S", name: "Lights S", color: "#F97316", category: "Lights" },
  { code: "T", name: "Lights T", color: "#F97316", category: "Lights" },
  { code: "U", name: "Lights U", color: "#F97316", category: "Lights" },
  { code: "V", name: "Lights V", color: "#F97316", category: "Lights" },
  { code: "W", name: "Lights W", color: "#F97316", category: "Lights" },
  { code: "X", name: "Lights X", color: "#F97316", category: "Lights" },
  { code: "Y", name: "Lights Y", color: "#F97316", category: "Lights" },
  { code: "Z", name: "Lights Z", color: "#F97316", category: "Lights" },
  { code: "LT-2X4", name: "Fixture 2x4 LED", color: "#F97316", category: "Lights" },
  { code: "LT-2X2", name: "Fixture 2x2 LED", color: "#F97316", category: "Lights" },
  { code: "LT-1X4", name: "Fixture 1x4 LED", color: "#F97316", category: "Lights" },
  { code: "LT-DN", name: "Downlight (Round/Square)", color: "#F97316", category: "Lights" },
  { code: "LT-STRIP", name: "Strip/Wrap", color: "#F97316", category: "Lights" },
  { code: "LT-HB", name: "High Bay", color: "#F97316", category: "Lights" },
  { code: "LT-PEND", name: "Pendant/Decorative", color: "#F97316", category: "Lights" },
  { code: "LT-LINEAR", name: "Linear Slot", color: "#F97316", category: "Lights" },
  { code: "LT-TRACK", name: "Track + Head", color: "#F97316", category: "Lights" },
  { code: "LT-UC", name: "Under-Cabinet", color: "#F97316", category: "Lights" },
  { code: "LT-COVE", name: "Cove/Accent", color: "#F97316", category: "Lights" },
  { code: "EX", name: "Exit Sign", color: "#F97316", category: "Lights" },
  { code: "EXC", name: "Exit/Emergency Combo", color: "#F97316", category: "Lights" },
  { code: "EM", name: "Emergency Light (Unit)", color: "#F97316", category: "Lights" },
  { code: "EM-RH", name: "Remote Head (per head)", color: "#F97316", category: "Lights" },
  { code: "LT-WP", name: "Wallpack (Exterior)", color: "#F97316", category: "Lights" },
  { code: "LT-CANOPY", name: "Canopy Light", color: "#F97316", category: "Lights" },
  { code: "LT-STEP", name: "Step/Path Light", color: "#F97316", category: "Lights" },

  // --------------------------- RECEPTACLES ---------------------------
  { code: "REC", name: "Duplex Receptacle", color: "#3B82F6", category: "Receptacles" },
  { code: "QR", name: "Quad Receptacle", color: "#3B82F6", category: "Receptacles" },
  { code: "REC-GFCI", name: "GFCI Receptacle", color: "#1D4ED8", category: "Receptacles" },
  { code: "REC-WP-GFCI", name: "GFCI (Weatherproof)", color: "#1D4ED8", category: "Receptacles" },
  { code: "REC-IG", name: "Isolated Ground Receptacle", color: "#1E40AF", category: "Receptacles" },
  { code: "REC-USB", name: "USB Receptacle", color: "#2563EB", category: "Receptacles" },
  { code: "REC-FLR", name: "Floor Box Power", color: "#2563EB", category: "Receptacles" },
  { code: "REC-FURN", name: "Furniture Feed", color: "#2563EB", category: "Receptacles" },
  { code: "REC-208", name: "208/240V Receptacle", color: "#1E40AF", category: "Receptacles" },
  { code: "REC-TL-20", name: "Twist-Lock 20A", color: "#1E40AF", category: "Receptacles" },
  { code: "REC-TL-30", name: "Twist-Lock 30A", color: "#1E40AF", category: "Receptacles" },

  // --------------------------- SWITCHES ---------------------------
  { code: "SW", name: "Switch (SP)", color: "#60A5FA", category: "Switches" },
  { code: "SW-3W", name: "Switch (3-way)", color: "#60A5FA", category: "Switches" },
  { code: "SW-4W", name: "Switch (4-way)", color: "#60A5FA", category: "Switches" },
  { code: "KS", name: "Key Switch", color: "#60A5FA", category: "Switches" },
  { code: "SPST", name: "SPST", color: "#60A5FA", category: "Switches" },
  { code: "DPST", name: "DPST", color: "#60A5FA", category: "Switches" },

  // --------------------------- STUB-UPS ---------------------------
  { code: "TP", name: "Telephone Stub-Up", color: "#38BDF8", category: "Stub-Ups" },
  { code: "CATV", name: "CATV Stub-Up", color: "#38BDF8", category: "Stub-Ups" },
  { code: "D", name: "Data Stub-Up", color: "#38BDF8", category: "Stub-Ups" },
  { code: "FSU", name: "Floor Stub-Up", color: "#38BDF8", category: "Stub-Ups" },
  { code: "STU-GEN", name: "Generator Control Stub-Up", color: "#38BDF8", category: "Stub-Ups" },

  // --------------------------- FIRE ALARM ---------------------------
  { code: "FA", name: "Fire Alarm (Generic)", color: "#B91C1C", category: "Fire Alarm" },
  { code: "FACP", name: "FA Control Panel", color: "#B91C1C", category: "Fire Alarm" },
  { code: "NAC", name: "NAC/Booster Panel", color: "#B91C1C", category: "Fire Alarm" },
  { code: "SD", name: "Smoke Detector", color: "#DC2626", category: "Fire Alarm" },
  { code: "HD", name: "Heat Detector", color: "#DC2626", category: "Fire Alarm" },
  { code: "DD", name: "Duct Detector", color: "#B91C1C", category: "Fire Alarm" },
  { code: "HS", name: "Horn/Strobe", color: "#EF4444", category: "Fire Alarm" },
  { code: "H", name: "Horn", color: "#EF4444", category: "Fire Alarm" },
  { code: "L", name: "Strobe", color: "#EF4444", category: "Fire Alarm" },
  { code: "PS", name: "Pull Station", color: "#EF4444", category: "Fire Alarm" },
  { code: "RIL", name: "Remote Indicator Light", color: "#EF4444", category: "Fire Alarm" },
  { code: "MS", name: "Manual Station", color: "#EF4444", category: "Fire Alarm" },
  { code: "SM", name: "Smoke Monitor", color: "#DC2626", category: "Fire Alarm" },
  { code: "VE", name: "Voice Evac Speaker/Strobe", color: "#B91C1C", category: "Fire Alarm" },
  { code: "ISO", name: "SLC Isolator Module", color: "#B91C1C", category: "Fire Alarm" },
  { code: "MM", name: "Monitor Module", color: "#B91C1C", category: "Fire Alarm" },
  { code: "CM", name: "Control Module", color: "#B91C1C", category: "Fire Alarm" },
  { code: "SS", name: "Supervisory Switch (Flow/Tamper)", color: "#B91C1C", category: "Fire Alarm" },

  // --------------------------- BREAKERS ---------------------------
  { code: "SPD", name: "Surge Protector (SPD)", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-20/1", name: "Breaker 20/1", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-20/2", name: "Breaker 20/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-20/3", name: "Breaker 20/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-30/1", name: "Breaker 30/1", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-30/2", name: "Breaker 30/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-30/3", name: "Breaker 30/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-40/2", name: "Breaker 40/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-40/3", name: "Breaker 40/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-50/2", name: "Breaker 50/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-50/3", name: "Breaker 50/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-60/2", name: "Breaker 60/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-60/3", name: "Breaker 60/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-70/3", name: "Breaker 70/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-80/2", name: "Breaker 80/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-80/3", name: "Breaker 80/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-90/2", name: "Breaker 90/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-90/3", name: "Breaker 90/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-100/2", name: "Breaker 100/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-100/3", name: "Breaker 100/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-125/2", name: "Breaker 125/2", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-125/3", name: "Breaker 125/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-150/3", name: "Breaker 150/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-200/3", name: "Breaker 200/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-250/3", name: "Breaker 250/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-300/3", name: "Breaker 300/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-350/3", name: "Breaker 350/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-400/3", name: "Breaker 400/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-500/3", name: "Breaker 500/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-600/3", name: "Breaker 600/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-800/3", name: "Breaker 800/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-1000/3", name: "Breaker 1000/3", color: "#0EA5E9", category: "Breakers" },
  { code: "BRK-1200/3", name: "Breaker 1200/3", color: "#0EA5E9", category: "Breakers" },

  // --------------------------- PANELS / GEAR ---------------------------
  { code: "SWGR", name: "Switchgear", color: "#2563EB", category: "Panels" },
  { code: "SWBD", name: "Switchboard", color: "#2563EB", category: "Panels" },
  { code: "MDP", name: "Main Dist Panel", color: "#2563EB", category: "Panels" },
  { code: "LP", name: "Lighting Panel", color: "#2563EB", category: "Panels" },
  { code: "PP", name: "Power Panel", color: "#2563EB", category: "Panels" },
  { code: "SP", name: "Sub Panel", color: "#2563EB", category: "Panels" },
  { code: "MTR-BASE", name: "Utility Meter Base", color: "#2563EB", category: "Panels" },
  { code: "CT-CAB", name: "CT Cabinet", color: "#2563EB", category: "Panels" },
  { code: "MTR-STACK", name: "Meter Stack", color: "#2563EB", category: "Panels" },
  { code: "ATS", name: "Automatic Transfer Switch", color: "#0EA5E9", category: "Panels" },
  { code: "MTS", name: "Manual Transfer Switch", color: "#0EA5E9", category: "Panels" },
  { code: "GEN", name: "Generator (Standby)", color: "#2563EB", category: "Panels" },
  { code: "UPS", name: "UPS System", color: "#2563EB", category: "Panels" },
  { code: "PDU", name: "Power Distribution Unit", color: "#2563EB", category: "Panels" },
  { code: "XFMR-15", name: "Transformer 15 kVA", color: "#1E40AF", category: "Panels" },
  { code: "XFMR-30", name: "Transformer 30 kVA", color: "#1E40AF", category: "Panels" },
  { code: "XFMR-45", name: "Transformer 45 kVA", color: "#1E40AF", category: "Panels" },
  { code: "XFMR-75", name: "Transformer 75 kVA", color: "#1E40AF", category: "Panels" },
  { code: "XFMR-112", name: "Transformer 112.5 kVA", color: "#1E40AF", category: "Panels" },
  { code: "XFMR-150", name: "Transformer 150 kVA", color: "#1E40AF", category: "Panels" },
  { code: "XFMR-225", name: "Transformer 225 kVA", color: "#1E40AF", category: "Panels" },

  // … (continue through Disconnects, Raceways, Conductors & Feeders, Data/Comm, Security, AV/Sound, BAS, Site Power, Demolition/Temporary, Miscellaneous)
];
