// src/constants/masterTags.ts
export type MasterTag = {
  code: string;
  name: string;
  color: string;
  category: string;
  customMaterialCost?: number;
  customLaborHours?: number;
};

export const DEFAULT_MASTER_TAGS: MasterTag[] = [
  // --------------------------- LIGHTS (interior/exterior) ---------------------------
  { code: 'A', name: 'Lights A', color: '#F97316', category: 'Lights' },
  { code: 'A1', name: 'Lights A1 (Night Light)', color: '#F97316', category: 'Lights' },
  { code: 'B', name: 'Lights B', color: '#F97316', category: 'Lights' },
  { code: 'C', name: 'Lights C', color: '#F97316', category: 'Lights' },
  { code: 'D', name: 'Lights D', color: '#F97316', category: 'Lights' },
  { code: 'E', name: 'Lights E', color: '#F97316', category: 'Lights' },
  { code: 'F', name: 'Lights F', color: '#F97316', category: 'Lights' },
  { code: 'G', name: 'Lights G', color: '#F97316', category: 'Lights' },
  { code: 'H', name: 'Lights H', color: '#F97316', category: 'Lights' },
  { code: 'I', name: 'Lights I', color: '#F97316', category: 'Lights' },
  { code: 'J', name: 'Lights J', color: '#F97316', category: 'Lights' },
  { code: 'K', name: 'Lights K', color: '#F97316', category: 'Lights' },
  { code: 'L', name: 'Lights L', color: '#F97316', category: 'Lights' },
  { code: 'M', name: 'Lights M', color: '#F97316', category: 'Lights' },
  { code: 'N', name: 'Lights N', color: '#F97316', category: 'Lights' },
  { code: 'O', name: 'Lights O', color: '#F97316', category: 'Lights' },
  { code: 'P', name: 'Lights P', color: '#F97316', category: 'Lights' },
  { code: 'Q', name: 'Lights Q', color: '#F97316', category: 'Lights' },
  { code: 'R', name: 'Lights R', color: '#F97316', category: 'Lights' },
  { code: 'S', name: 'Lights S', color: '#F97316', category: 'Lights' },
  { code: 'T', name: 'Lights T', color: '#F97316', category: 'Lights' },
  { code: 'U', name: 'Lights U', color: '#F97316', category: 'Lights' },
  { code: 'V', name: 'Lights V', color: '#F97316', category: 'Lights' },
  { code: 'W', name: 'Lights W', color: '#F97316', category: 'Lights' },
  { code: 'X', name: 'Lights X', color: '#F97316', category: 'Lights' },
  { code: 'Y', name: 'Lights Y', color: '#F97316', category: 'Lights' },
  { code: 'Z', name: 'Lights Z', color: '#F97316', category: 'Lights' },
  { code: 'LT-2X4', name: 'Fixture 2x4 LED', color: '#F97316', category: 'Lights' },
  { code: 'LT-2X2', name: 'Fixture 2x2 LED', color: '#F97316', category: 'Lights' },
  { code: 'LT-1X4', name: 'Fixture 1x4 LED', color: '#F97316', category: 'Lights' },
  { code: 'LT-DN', name: 'Downlight (Round/Square)', color: '#F97316', category: 'Lights' },
  { code: 'LT-STRIP', name: 'Strip/Wrap', color: '#F97316', category: 'Lights' },
  { code: 'LT-HB', name: 'High Bay', color: '#F97316', category: 'Lights' },
  { code: 'LT-PEND', name: 'Pendant/Decorative', color: '#F97316', category: 'Lights' },
  { code: 'LT-LINEAR', name: 'Linear Slot', color: '#F97316', category: 'Lights' },
  { code: 'LT-TRACK', name: 'Track + Head', color: '#F97316', category: 'Lights' },
  { code: 'LT-UC', name: 'Under-Cabinet', color: '#F97316', category: 'Lights' },
  { code: 'LT-COVE', name: 'Cove/Accent', color: '#F97316', category: 'Lights' },
  { code: 'EX', name: 'Exit Sign', color: '#F97316', category: 'Lights' },
  { code: 'EXC', name: 'Exit/Emergency Combo', color: '#F97316', category: 'Lights' },
  { code: 'EM', name: 'Emergency Light (Unit)', color: '#F97316', category: 'Lights' },
  { code: 'EM-RH', name: 'Remote Head (per head)', color: '#F97316', category: 'Lights' },
  { code: 'LT-WP', name: 'Wallpack (Exterior)', color: '#F97316', category: 'Lights' },
  { code: 'LT-CANOPY', name: 'Canopy Light', color: '#F97316', category: 'Lights' },
  { code: 'LT-STEP', name: 'Step/Path Light', color: '#F97316', category: 'Lights' },

  // --------------------------- RECEPTACLES ---------------------------
  { code: 'REC', name: 'Duplex Receptacle', color: '#3B82F6', category: 'Receptacles' },
  { code: 'QR', name: 'Quad Receptacle', color: '#3B82F6', category: 'Receptacles' },
  { code: 'GFI', name: 'GFCI Receptacle (Homerun every 6)', color: '#1D4ED8', category: 'Receptacles' },
  { code: 'REC-GFCI', name: 'GFCI Receptacle (Homerun every 6)', color: '#1D4ED8', category: 'Receptacles' },
  { code: 'REC-WP-GFCI', name: 'GFCI (Weatherproof)', color: '#1D4ED8', category: 'Receptacles' },
  { code: 'REC-IG', name: 'Isolated Ground Receptacle', color: '#1E40AF', category: 'Receptacles' },
  { code: 'REC-USB', name: 'USB Receptacle', color: '#2563EB', category: 'Receptacles' },
  { code: 'REC-FLR', name: 'Floor Box Power', color: '#2563EB', category: 'Receptacles' },
  { code: 'REC-FURN', name: 'Furniture Feed', color: '#2563EB', category: 'Receptacles' },
  { code: 'REC-208', name: '208/240V Receptacle', color: '#1E40AF', category: 'Receptacles' },
  { code: 'REC-TL-20', name: 'Twist-Lock 20A', color: '#1E40AF', category: 'Receptacles' },
  { code: 'REC-TL-30', name: 'Twist-Lock 30A', color: '#1E40AF', category: 'Receptacles' },

  // --------------------------- SWITCHES ---------------------------
  { code: 'SW', name: 'Switch (SP)', color: '#60A5FA', category: 'Switches' },
  { code: 'SW-3W', name: 'Switch (3-way)', color: '#60A5FA', category: 'Switches' },
  { code: 'SW-4W', name: 'Switch (4-way)', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM', name: 'Dimmer Switch (SP)', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM-3W', name: 'Dimmer Switch (3-way)', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM-4W', name: 'Dimmer Switch (4-way)', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM-WC', name: 'Dimming Wall Control Station', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM-ML', name: 'Multi-Location Dimmer', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM-1000W', name: 'Dimmer 1000W', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM-1500W', name: 'Dimmer 1500W', color: '#60A5FA', category: 'Switches' },
  { code: 'DIM-2000W', name: 'Dimmer 2000W', color: '#60A5FA', category: 'Switches' },
  { code: 'KS', name: 'Key Switch', color: '#60A5FA', category: 'Switches' },
  { code: 'SPST', name: 'SPST', color: '#60A5FA', category: 'Switches' },
  { code: 'DPST', name: 'DPST', color: '#60A5FA', category: 'Switches' },

  // --------------------------- STUB-UPS ---------------------------
  { code: 'TP', name: 'Telephone Stub-Up', color: '#38BDF8', category: 'Stub-Ups' },
  { code: 'CATV', name: 'CATV Stub-Up', color: '#38BDF8', category: 'Stub-Ups' },
  { code: 'DATA-SU', name: 'Data Stub-Up', color: '#38BDF8', category: 'Stub-Ups' },
  { code: 'FSU', name: 'Floor Stub-Up', color: '#38BDF8', category: 'Stub-Ups' },
  { code: 'STU-GEN', name: 'Generator Control Stub-Up', color: '#38BDF8', category: 'Stub-Ups' },

  // --------------------------- FIRE ALARM ---------------------------
  { code: 'FA', name: 'Fire Alarm (Generic)', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'FACP', name: 'FA Control Panel', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'NAC', name: 'NAC/Booster Panel', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'SD', name: 'Smoke Detector', color: '#DC2626', category: 'Fire Alarm' },
  { code: 'HD', name: 'Heat Detector', color: '#DC2626', category: 'Fire Alarm' },
  { code: 'DD', name: 'Duct Detector', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'HS', name: 'Horn/Strobe', color: '#EF4444', category: 'Fire Alarm' },
  { code: 'H', name: 'Horn', color: '#EF4444', category: 'Fire Alarm' },
  { code: 'L', name: 'Strobe', color: '#EF4444', category: 'Fire Alarm' },
  { code: 'PS', name: 'Pull Station', color: '#EF4444', category: 'Fire Alarm' },
  { code: 'RIL', name: 'Remote Indicator Light', color: '#EF4444', category: 'Fire Alarm' },
  { code: 'MS', name: 'Manual Station', color: '#EF4444', category: 'Fire Alarm' },
  { code: 'SM', name: 'Smoke Monitor', color: '#DC2626', category: 'Fire Alarm' },
  { code: 'VE', name: 'Voice Evac Speaker/Strobe', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'ISO', name: 'SLC Isolator Module', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'MM', name: 'Monitor Module', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'CM', name: 'Control Module', color: '#B91C1C', category: 'Fire Alarm' },
  { code: 'SS', name: 'Supervisory Switch (Flow/Tamper)', color: '#B91C1C', category: 'Fire Alarm' },

  // --------------------------- BREAKERS ---------------------------
  { code: 'SPD', name: 'Surge Protector (SPD)', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-20/1', name: 'Breaker 20/1', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-20/2', name: 'Breaker 20/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-20/3', name: 'Breaker 20/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-30/1', name: 'Breaker 30/1', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-30/2', name: 'Breaker 30/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-30/3', name: 'Breaker 30/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-40/2', name: 'Breaker 40/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-40/3', name: 'Breaker 40/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-50/2', name: 'Breaker 50/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-50/3', name: 'Breaker 50/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-60/2', name: 'Breaker 60/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-60/3', name: 'Breaker 60/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-70/3', name: 'Breaker 70/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-80/2', name: 'Breaker 80/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-80/3', name: 'Breaker 80/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-90/2', name: 'Breaker 90/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-90/3', name: 'Breaker 90/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-100/2', name: 'Breaker 100/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-100/3', name: 'Breaker 100/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-125/2', name: 'Breaker 125/2', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-125/3', name: 'Breaker 125/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-150/3', name: 'Breaker 150/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-200/3', name: 'Breaker 200/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-250/3', name: 'Breaker 250/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-300/3', name: 'Breaker 300/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-350/3', name: 'Breaker 350/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-400/3', name: 'Breaker 400/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-500/3', name: 'Breaker 500/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-600/3', name: 'Breaker 600/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-800/3', name: 'Breaker 800/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-1000/3', name: 'Breaker 1000/3', color: '#0EA5E9', category: 'Breakers' },
  { code: 'BRK-1200/3', name: 'Breaker 1200/3', color: '#0EA5E9', category: 'Breakers' },

  // --------------------------- PANELS / GEAR ---------------------------
  { code: 'SWGR', name: 'Switchgear', color: '#2563EB', category: 'Panels' },
  { code: 'SWBD', name: 'Switchboard', color: '#2563EB', category: 'Panels' },
  { code: 'MDP', name: 'Main Dist Panel', color: '#2563EB', category: 'Panels' },
  { code: 'LP', name: 'Lighting Panel', color: '#2563EB', category: 'Panels' },
  { code: 'PP', name: 'Power Panel', color: '#2563EB', category: 'Panels' },
  { code: 'SP', name: 'Sub Panel', color: '#2563EB', category: 'Panels' },
  { code: 'MTR-BASE', name: 'Utility Meter Base', color: '#2563EB', category: 'Panels' },
  { code: 'CT-CAB', name: 'CT Cabinet', color: '#2563EB', category: 'Panels' },
  { code: 'MTR-STACK', name: 'Meter Stack', color: '#2563EB', category: 'Panels' },
  { code: 'ATS', name: 'Automatic Transfer Switch', color: '#0EA5E9', category: 'Panels' },
  { code: 'MTS', name: 'Manual Transfer Switch', color: '#0EA5E9', category: 'Panels' },
  { code: 'GEN', name: 'Generator (Standby)', color: '#2563EB', category: 'Panels' },
  { code: 'UPS', name: 'UPS System', color: '#2563EB', category: 'Panels' },
  { code: 'PDU', name: 'Power Distribution Unit', color: '#2563EB', category: 'Panels' },
  { code: 'XFMR-15', name: 'Transformer 15 kVA', color: '#1E40AF', category: 'Panels' },
  { code: 'XFMR-30', name: 'Transformer 30 kVA', color: '#1E40AF', category: 'Panels' },
  { code: 'XFMR-45', name: 'Transformer 45 kVA', color: '#1E40AF', category: 'Panels' },
  { code: 'XFMR-75', name: 'Transformer 75 kVA', color: '#1E40AF', category: 'Panels' },
  { code: 'XFMR-112', name: 'Transformer 112.5 kVA', color: '#1E40AF', category: 'Panels' },
  { code: 'XFMR-150', name: 'Transformer 150 kVA', color: '#1E40AF', category: 'Panels' },
  { code: 'XFMR-225', name: 'Transformer 225 kVA', color: '#1E40AF', category: 'Panels' },

  // retain your existing panel ratings for quick selection
  { code: '125/MLO/2 Pole', name: '125/MLO/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '125/MB/2 Pole', name: '125/MB/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '150/MLO/2 Pole', name: '150/MLO/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '150/MB/2 Pole', name: '150/MB/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '200/MLO/2 Pole', name: '200/MLO/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '200/MB/2 Pole', name: '200/MB/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '225/MLO/2 Pole', name: '225/MLO/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '225/MB/2 Pole', name: '225/MB/2 Pole', color: '#2563EB', category: 'Panels' },
  { code: '125/MLO/3 Pole', name: '125/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '125/MB/3 Pole', name: '125/MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '150/MLO/3 Pole', name: '150/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '150/MB/3 Pole', name: '150/MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '200/MLO/3 Pole', name: '200/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '200/MB/3 Pole', name: '200/MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '225/MLO/3 Pole', name: '225/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '225/MB/3 Pole', name: '225/MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '300/MLO/3 Pole', name: '300/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '300/MB/3 Pole', name: '300/MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '400/MLO/3 Pole', name: '400/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '400/MB/3 Pole', name: '400/MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '600/MLO/3 Pole', name: '600/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '800/MLO/3 Pole', name: '800/MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '800/3MB/3 Pole', name: '800/3MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '1000/3MLO/3 Pole', name: '1000/3MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '1000/3MB/3 Pole', name: '1000/3MB/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '1200/3MLO/3 Pole', name: '1200/3MLO/3 Pole', color: '#2563EB', category: 'Panels' },
  { code: '1200/MB/3 Pole', name: '1200/MB/3 Pole', color: '#2563EB', category: 'Panels' },

  // --------------------------- DISCONNECTS ---------------------------
  { code: '30/2', name: 'Disconnect 30/2', color: '#0EA5E9', category: 'Disconnects' },
  { code: '30/3', name: 'Disconnect 30/3', color: '#0EA5E9', category: 'Disconnects' },
  { code: '60/2', name: 'Disconnect 60/2', color: '#0EA5E9', category: 'Disconnects' },
  { code: '60/3', name: 'Disconnect 60/3', color: '#0EA5E9', category: 'Disconnects' },
  { code: '100/2', name: 'Disconnect 100/2', color: '#0EA5E9', category: 'Disconnects' },
  { code: '100/3', name: 'Disconnect 100/3', color: '#0EA5E9', category: 'Disconnects' },
  { code: '200/2', name: 'Disconnect 200/2', color: '#0EA5E9', category: 'Disconnects' },
  { code: '200/3', name: 'Disconnect 200/3', color: '#0EA5E9', category: 'Disconnects' },
  { code: '400/2', name: 'Disconnect 400/2', color: '#0EA5E9', category: 'Disconnects' },
  { code: '400/3', name: 'Disconnect 400/3', color: '#0EA5E9', category: 'Disconnects' },
  { code: '600/2', name: 'Disconnect 600/2', color: '#0EA5E9', category: 'Disconnects' },
  { code: '600/3', name: 'Disconnect 600/3', color: '#0EA5E9', category: 'Disconnects' },
  { code: '30/2/WP', name: 'Disconnect 30/2 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '30/3/WP', name: 'Disconnect 30/3 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '60/2/WP', name: 'Disconnect 60/2 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '60/3/WP', name: 'Disconnect 60/3 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '100/2/WP', name: 'Disconnect 100/2 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '100/3/WP', name: 'Disconnect 100/3 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '200/2/WP', name: 'Disconnect 200/2 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '200/3/WP', name: 'Disconnect 200/3 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '400/2/WP', name: 'Disconnect 400/2 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '400/3/WP', name: 'Disconnect 400/3 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '600/2/WP', name: 'Disconnect 600/2 WP', color: '#38BDF8', category: 'Disconnects' },
  { code: '600/3/WP', name: 'Disconnect 600/3 WP', color: '#38BDF8', category: 'Disconnects' },

  // --------------------------- RACEWAYS & PATHWAYS ---------------------------
  // EMT (1/2" – 4")
  { code: 'EMT-1/2', name: 'EMT 1/2"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-3/4', name: 'EMT 3/4"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-1', name: 'EMT 1"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-1-1/4', name: 'EMT 1-1/4"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-1-1/2', name: 'EMT 1-1/2"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-2', name: 'EMT 2"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-2-1/2', name: 'EMT 2-1/2"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-3', name: 'EMT 3"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-3-1/2', name: 'EMT 3-1/2"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'EMT-4', name: 'EMT 4"', color: '#059669', category: 'Raceways & Pathways' },

  // PVC Sch40 / Sch80 (3/4" – 4")
  { code: 'PVC40-3/4', name: 'PVC Sch40 3/4"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'PVC40-1', name: 'PVC Sch40 1"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'PVC40-1-1/4', name: 'PVC Sch40 1-1/4"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'PVC40-1-1/2', name: 'PVC Sch40 1-1/2"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'PVC40-2', name: 'PVC Sch40 2"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'PVC40-3', name: 'PVC Sch40 3"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'PVC40-4', name: 'PVC Sch40 4"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'PVC80-1', name: 'PVC Sch80 1"', color: '#34D399', category: 'Raceways & Pathways' },
  { code: 'PVC80-1-1/2', name: 'PVC Sch80 1-1/2"', color: '#34D399', category: 'Raceways & Pathways' },
  { code: 'PVC80-2', name: 'PVC Sch80 2"', color: '#34D399', category: 'Raceways & Pathways' },

  // RGS/IMC, FMC/LFMC, ENT
  { code: 'RGS-1', name: 'RGS 1"', color: '#047857', category: 'Raceways & Pathways' },
  { code: 'RGS-2', name: 'RGS 2"', color: '#047857', category: 'Raceways & Pathways' },
  { code: 'IMC-1', name: 'IMC 1"', color: '#047857', category: 'Raceways & Pathways' },
  { code: 'FMC-3/4', name: 'FMC 3/4"', color: '#16A34A', category: 'Raceways & Pathways' },
  { code: 'LFMC-3/4', name: 'LFMC 3/4"', color: '#16A34A', category: 'Raceways & Pathways' },
  { code: 'ENT-3/4', name: 'ENT (Smurf) 3/4"', color: '#22C55E', category: 'Raceways & Pathways' },

  // Surface raceway / Wiremold
  { code: 'WM-3000', name: 'Wiremold 3000', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'WM-4000', name: 'Wiremold 4000', color: '#059669', category: 'Raceways & Pathways' },

  // Cable Tray
  { code: 'CTRAY-L-12', name: 'Cable Tray Ladder 12"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'CTRAY-L-18', name: 'Cable Tray Ladder 18"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'CTRAY-L-24', name: 'Cable Tray Ladder 24"', color: '#059669', category: 'Raceways & Pathways' },
  { code: 'CTRAY-B-12', name: 'Cable Tray Basket 12"', color: '#059669', category: 'Raceways & Pathways' },

  // Ductbank / Sleeves / Boxes
  { code: 'DB-4x4', name: 'Ductbank (4)×4"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'DB-6x4', name: 'Ductbank (6)×4"', color: '#10B981', category: 'Raceways & Pathways' },
  { code: 'SLV-4', name: 'Sleeve 4"', color: '#34D399', category: 'Raceways & Pathways' },
  { code: 'SLV-6', name: 'Sleeve 6"', color: '#34D399', category: 'Raceways & Pathways' },
  { code: 'PB-12x12', name: 'Pull Box 12x12', color: '#34D399', category: 'Raceways & Pathways' },
  { code: 'PB-24x24', name: 'Pull Box 24x24', color: '#34D399', category: 'Raceways & Pathways' },
  { code: 'HH-SITE', name: 'Handhole (Site)', color: '#34D399', category: 'Raceways & Pathways' },

  // --------------------------- CONDUCTORS & FEEDERS ---------------------------
  // THHN Cu branch sizes
  { code: 'THHN-#12', name: 'THHN #12 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-#10', name: 'THHN #10 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-#8', name: 'THHN #8 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-#6', name: 'THHN #6 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-#4', name: 'THHN #4 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-#3', name: 'THHN #3 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-#2', name: 'THHN #2 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-1', name: 'THHN 1 AWG Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-1/0', name: 'THHN 1/0 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-2/0', name: 'THHN 2/0 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-3/0', name: 'THHN 3/0 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-4/0', name: 'THHN 4/0 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-250', name: 'THHN 250 kcmil Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-350', name: 'THHN 350 kcmil Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-500', name: 'THHN 500 kcmil Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'THHN-600', name: 'THHN 600 kcmil Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'G-#10', name: 'EGC #10 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'G-#8', name: 'EGC #8 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'G-#6', name: 'EGC #6 Cu', color: '#047857', category: 'Conductors & Feeders' },
  { code: 'G-#4', name: 'EGC #4 Cu', color: '#047857', category: 'Conductors & Feeders' },

  // Aluminum feeders
  { code: 'AL-XHHW-1/0', name: 'Al XHHW-2 1/0', color: '#10B981', category: 'Conductors & Feeders' },
  { code: 'AL-XHHW-4/0', name: 'Al XHHW-2 4/0', color: '#10B981', category: 'Conductors & Feeders' },
  { code: 'AL-XHHW-250', name: 'Al XHHW-2 250 kcmil', color: '#10B981', category: 'Conductors & Feeders' },
  { code: 'AL-XHHW-350', name: 'Al XHHW-2 350 kcmil', color: '#10B981', category: 'Conductors & Feeders' },
  { code: 'AL-XHHW-500', name: 'Al XHHW-2 500 kcmil', color: '#10B981', category: 'Conductors & Feeders' },

  // MC Cabling
  { code: 'MC-12/2', name: 'MC 12/2', color: '#16A34A', category: 'Conductors & Feeders' },
  { code: 'MC-12/3', name: 'MC 12/3', color: '#16A34A', category: 'Conductors & Feeders' },
  { code: 'MC-10/3', name: 'MC 10/3', color: '#16A34A', category: 'Conductors & Feeders' },
  { code: 'MC-8/3', name: 'MC 8/3', color: '#16A34A', category: 'Conductors & Feeders' },
  { code: 'MC-6/3', name: 'MC 6/3', color: '#16A34A', category: 'Conductors & Feeders' },

  // --------------------------- DATA / COMMUNICATIONS ---------------------------
  { code: 'DATA-JACK', name: 'Data Jack (Cat6)', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'DATA-JACK-6A', name: 'Data Jack (Cat6A)', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'DATA-PLATE-1G', name: 'Faceplate 1-Gang', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'DATA-PLATE-2G', name: 'Faceplate 2-Gang', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'WAP', name: 'Wireless Access Point', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'RACK-2P', name: 'Rack 2-Post', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'RACK-4P', name: 'Rack 4-Post', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'PATCH-24', name: 'Patch Panel 24-Port', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'PATCH-48', name: 'Patch Panel 48-Port', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'JHOOK-2', name: 'J-Hook 2"', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'LAD-RACK-12', name: 'Ladder Rack 12"', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'LAD-RACK-18', name: 'Ladder Rack 18"', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'FIBER-6SM', name: 'Fiber 6-Strand SM', color: '#8B5CF6', category: 'Data/Communications' },
  { code: 'FIBER-12MM', name: 'Fiber 12-Strand MM', color: '#8B5CF6', category: 'Data/Communications' },

  // --------------------------- SECURITY ---------------------------
  { code: 'CAM', name: 'IP Camera', color: '#7C3AED', category: 'Security' },
  { code: 'NVR', name: 'NVR/Recorder', color: '#7C3AED', category: 'Security' },
  { code: 'CARD', name: 'Card Reader', color: '#7C3AED', category: 'Security' },
  { code: 'REX', name: 'Request-to-Exit', color: '#7C3AED', category: 'Security' },
  { code: 'DC', name: 'Door Contact', color: '#7C3AED', category: 'Security' },
  { code: 'MAG', name: 'Mag Lock', color: '#7C3AED', category: 'Security' },
  { code: 'SEC-PS', name: 'Security Power Supply', color: '#7C3AED', category: 'Security' },

  // --------------------------- AV / SOUND ---------------------------
  { code: 'SPKR-CLG', name: 'Ceiling Speaker', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'VOL', name: 'Volume Control', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'PROJ', name: 'Projector', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'SCRN', name: 'Motorized Screen', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'DSP-AMP', name: 'DSP/Amplifier', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'DISPLAY-55', name: 'Display 55"', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'DISPLAY-75', name: 'Display 75"', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'HDBaseT', name: 'HDBaseT Tx/Rx', color: '#6D28D9', category: 'AV / Sound' },
  { code: 'AV-RACK', name: 'AV Rack', color: '#6D28D9', category: 'AV / Sound' },

  // --------------------------- BAS / CONTROLS ---------------------------
  { code: 'STAT', name: 'Thermostat', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'TSENS', name: 'Temp Sensor', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'HSENS', name: 'Humidity Sensor', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'CO2', name: 'CO2 Sensor', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'DDC', name: 'DDC Panel', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'VAV-CTRL', name: 'VAV Controller', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'BAS-PS', name: 'BAS Power Supply', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'TCLK', name: 'Time Clock', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'TC-ASTRO', name: 'Astronomical Time Clock', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'TC-DIGITAL', name: 'Digital Time Clock (7-day)', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'SPEC-EQUIP300', name: 'Special Equipment Hookup $300', color: '#8B5CF6', category: 'Miscellaneous' },
  { code: 'SPEC-EQUIP150', name: 'Special Equipment Hookup $150', color: '#8B5CF6', category: 'Miscellaneous' },
  { code: 'SPEC-EQUIP50', name: 'Special Equipment Hookup $50', color: '#8B5CF6', category: 'Miscellaneous' },
  { code: 'PHOTO', name: 'Photocell', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'PHOTO-TWST', name: 'Photocell Twist-Lock', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'CONTACTOR', name: 'Lighting Contactor', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'CONT-30A', name: 'Contactor 30A', color: '#22C55E', category: 'BAS/Controls' },
  { code: 'CONT-60A', name: 'Contactor 60A', color: '#22C55E', category: 'BAS/Controls' },

  // --------------------------- LIGHTING CONTROL PANELS ---------------------------
  { code: 'LCP', name: 'Lighting Control Panel', color: '#8B5CF6', category: 'Lighting Control' },
  { code: 'LCP-1', name: 'Lighting Control Panel LCP-1', color: '#8B5CF6', category: 'Lighting Control' },
  { code: 'LCP-2', name: 'Lighting Control Panel LCP-2', color: '#8B5CF6', category: 'Lighting Control' },
  { code: 'LCP-3', name: 'Lighting Control Panel LCP-3', color: '#8B5CF6', category: 'Lighting Control' },
  { code: 'WS', name: 'Wall Control Station', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'WS-4', name: 'Wall Control Station (4-Scene)', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'WS-8', name: 'Wall Control Station (8-Scene)', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'OS', name: 'Occupancy Sensor', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'OS-CEILING', name: 'Ceiling Occupancy Sensor', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'OS-WALL', name: 'Wall Occupancy Sensor', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'DS', name: 'Daylight Sensor', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'GW', name: 'Network Bridge/Gateway', color: '#A78BFA', category: 'Lighting Control' },
  { code: 'GW-BACNET', name: 'BACnet Gateway', color: '#A78BFA', category: 'Lighting Control' },

  // --------------------------- SITE POWER / SITE LIGHTING ---------------------------
  { code: 'POLE-25', name: 'Site Pole 25\' (less head)', color: '#A16207', category: 'Site Power' },
  { code: 'POLE-30', name: 'Site Pole 30\' (less head)', color: '#A16207', category: 'Site Power' },
  { code: 'POLE-LIGHT', name: 'Pole Light Complete', color: '#A16207', category: 'Site Power' },
  { code: 'BOLLARD', name: 'Bollard Light', color: '#A16207', category: 'Site Power' },
  { code: 'SITE-LP-HEAD', name: 'Site Pole Head', color: '#A16207', category: 'Site Power' },
  { code: 'SITE-RECP', name: 'Site Receptacle Pedestal', color: '#A16207', category: 'Site Power' },
  { code: 'EVSE-40A', name: 'EV Charger 40A', color: '#A16207', category: 'Site Power' },
  { code: 'EVSE-80A', name: 'EV Charger 80A', color: '#A16207', category: 'Site Power' },
  { code: 'EV-SINGLE', name: 'Single Unit EV Charger', color: '#A16207', category: 'Site Power' },
  { code: 'EV-DUAL', name: 'Dual Unit EV Charger', color: '#A16207', category: 'Site Power' },
  { code: 'SITE-HH', name: 'Handhole (Power/Data)', color: '#A16207', category: 'Site Power' },
  { code: 'POLE-BASE', name: 'Pole Base', color: '#A16207', category: 'Site Power' },
  { code: 'POWER-POLE', name: 'Power Pole Installation', color: '#A16207', category: 'Site Power' },
  { code: 'TRENCH', name: 'Trenching 6"x36"', color: '#92400E', category: 'Site Power' },
  { code: 'BACKHOE', name: 'Backhoe Work', color: '#92400E', category: 'Site Power' },

  // --------------------------- DEMOLITION / TEMPORARY ---------------------------
  { code: 'DEM-LT', name: 'Demo Light Fixture', color: '#9CA3AF', category: 'Demolition / Temporary' },
  { code: 'DEM-REC', name: 'Demo Receptacle', color: '#9CA3AF', category: 'Demolition / Temporary' },
  { code: 'DEM-SW', name: 'Demo Switch', color: '#9CA3AF', category: 'Demolition / Temporary' },
  { code: 'DEM-PNL', name: 'Demo Panel/Gear', color: '#9CA3AF', category: 'Demolition / Temporary' },
  { code: 'TEMP-PP', name: 'Temp Power Pole', color: '#9CA3AF', category: 'Demolition / Temporary' },
  { code: 'TEMP-LTS-100', name: 'Temp Light String (per 100\')', color: '#9CA3AF', category: 'Demolition / Temporary' },

  // --------------------------- TRANSFORMERS ---------------------------
  { code: 'XFMR-25KVA', name: 'Transformer 25 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-30KVA', name: 'Transformer 30 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-45KVA', name: 'Transformer 45 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-75KVA', name: 'Transformer 75 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-112KVA', name: 'Transformer 112.5 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-150KVA', name: 'Transformer 150 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-225KVA', name: 'Transformer 225 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-300KVA', name: 'Transformer 300 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-500KVA', name: 'Transformer 500 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-750KVA', name: 'Transformer 750 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-1000KVA', name: 'Transformer 1000 kVA', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-208-480', name: 'Transformer 208/480V', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-PAD', name: 'Transformer Pad (Site)', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-PAD-L', name: 'Transformer Pad Large', color: '#1E40AF', category: 'Transformers' },
  { code: 'XFMR-VAULT', name: 'Transformer Vault', color: '#1E40AF', category: 'Transformers' },

  // --------------------------- GENERATORS & BACKUP POWER ---------------------------
  { code: 'GEN-INSTALL', name: 'Generator Installation', color: '#2563EB', category: 'Generators' },
  { code: 'GENERATOR', name: 'Generator Unit', color: '#2563EB', category: 'Generators' },

  // --------------------------- BACKBOARDS ---------------------------
  { code: 'BACKBOARD', name: 'Backboard 4x8x3/4"', color: '#78350F', category: 'Backboards' },
  { code: 'BB-4X8', name: 'Plywood Backboard 4x8', color: '#78350F', category: 'Backboards' },

  // --------------------------- TELEPHONE ---------------------------
  { code: 'TEL-OUTLET', name: 'Telephone Outlet', color: '#38BDF8', category: 'Telephone' },
  { code: 'TEL-GND', name: 'Telephone Backboard Ground', color: '#38BDF8', category: 'Telephone' },

  // --------------------------- ENGINEERING & STUDIES ---------------------------
  { code: 'STUDY', name: 'Coordination Study', color: '#6B7280', category: 'Engineering' },
  { code: 'COORD-STUDY', name: 'Electrical Coordination Study', color: '#6B7280', category: 'Engineering' },

  // --------------------------- CONDUIT SUPPORT ---------------------------
  { code: 'ROOF-SUPPORT', name: 'Conduit Roof Support', color: '#059669', category: 'Conduit Support' },
  { code: 'UNISTRUT-ROOF', name: 'Roof Top Unistrut Support', color: '#059669', category: 'Conduit Support' },

  // --------------------------- ELECTRICAL MATERIALS ---------------------------
  { code: 'BOX-4SQ', name: '4" Square Box 1-1/2" Deep', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BOX-4SQ-2', name: '4" Square Box 2-1/8" Deep', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BOX-411', name: '4-11/16" Square Box', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BOX-OCT', name: 'Octagon Box 1-1/2"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BOX-DEVICE', name: 'Device Box (Single Gang)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BOX-2G', name: 'Device Box (2-Gang)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BOX-3G', name: 'Device Box (3-Gang)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BOX-4G', name: 'Device Box (4-Gang)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'RING-4SQ', name: '4" Square Cover/Ring', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'RING-411', name: '4-11/16" Square Cover/Ring', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'PLATE-1G', name: 'Wall Plate 1-Gang', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'PLATE-2G', name: 'Wall Plate 2-Gang', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'PLATE-3G', name: 'Wall Plate 3-Gang', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'PLATE-BLK', name: 'Blank Plate', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'CONN-EMT-1/2', name: 'EMT Connector 1/2"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'CONN-EMT-3/4', name: 'EMT Connector 3/4"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'CONN-EMT-1', name: 'EMT Connector 1"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'COUP-EMT-1/2', name: 'EMT Coupling 1/2"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'COUP-EMT-3/4', name: 'EMT Coupling 3/4"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'COUP-EMT-1', name: 'EMT Coupling 1"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'STRAP-1/2', name: '1/2" Conduit Strap', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'STRAP-3/4', name: '3/4" Conduit Strap', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'STRAP-1', name: '1" Conduit Strap', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'LB-1/2', name: 'LB Conduit Body 1/2"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'LB-3/4', name: 'LB Conduit Body 3/4"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'LB-1', name: 'LB Conduit Body 1"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'WIRENUTS-SM', name: 'Wire Nuts (Small)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'WIRENUTS-MD', name: 'Wire Nuts (Medium)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'WIRENUTS-LG', name: 'Wire Nuts (Large)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'TAPE-ELEC', name: 'Electrical Tape', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'TAPE-PHASE', name: 'Phase Tape (Set)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'ANCHOR-WEDGE', name: 'Wedge Anchor 3/8"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'ANCHOR-TAP', name: 'Tapcon Screw 1/4"', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'THREADED-3/8', name: '3/8" Threaded Rod', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'BEAM-CLAMP', name: 'Beam Clamp', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'UNISTRUT-10', name: 'Unistrut 1-5/8" (10ft)', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'JBOX-1212', name: 'Pull Box 12x12x6', color: '#4B5563', category: 'Electrical Materials' },
  { code: 'JBOX-2424', name: 'Pull Box 24x24x8', color: '#4B5563', category: 'Electrical Materials' },

  // --------------------------- MOTOR STARTERS & CONTROLS ---------------------------
  { code: 'MS-COMBO', name: 'Motor Starter Combo (Disconnect + Starter)', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-1HP', name: 'Motor Starter 1 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-2HP', name: 'Motor Starter 2 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-3HP', name: 'Motor Starter 3 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-5HP', name: 'Motor Starter 5 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-7.5HP', name: 'Motor Starter 7.5 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-10HP', name: 'Motor Starter 10 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-15HP', name: 'Motor Starter 15 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-20HP', name: 'Motor Starter 20 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-25HP', name: 'Motor Starter 25 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'MS-30HP', name: 'Motor Starter 30 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'VFD-1HP', name: 'VFD 1 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'VFD-2HP', name: 'VFD 2 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'VFD-3HP', name: 'VFD 3 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'VFD-5HP', name: 'VFD 5 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'VFD-10HP', name: 'VFD 10 HP', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'SOFT-START', name: 'Soft Starter', color: '#7C2D12', category: 'Motor Controls' },
  { code: 'HOA', name: 'Hand-Off-Auto Station', color: '#7C2D12', category: 'Motor Controls' },

  // --------------------------- GROUNDING ---------------------------
  { code: 'GRD-ROD', name: 'Ground Rod 8ft x 5/8"', color: '#065F46', category: 'Grounding' },
  { code: 'GRD-ROD-10', name: 'Ground Rod 10ft x 5/8"', color: '#065F46', category: 'Grounding' },
  { code: 'GRD-CLAMP', name: 'Ground Rod Clamp', color: '#065F46', category: 'Grounding' },
  { code: 'GRD-WIRE-#6', name: 'Ground Wire #6 Cu (LF)', color: '#065F46', category: 'Grounding' },
  { code: 'GRD-WIRE-#4', name: 'Ground Wire #4 Cu (LF)', color: '#065F46', category: 'Grounding' },
  { code: 'GRD-WIRE-#2', name: 'Ground Wire #2 Cu (LF)', color: '#065F46', category: 'Grounding' },
  { code: 'GRD-BAR', name: 'Ground Bus Bar', color: '#065F46', category: 'Grounding' },
  { code: 'CADWELD', name: 'Cadweld Connection', color: '#065F46', category: 'Grounding' },
  { code: 'UFER', name: 'Ufer Ground (Concrete Encased)', color: '#065F46', category: 'Grounding' },

  // --------------------------- BUSWAY & PLUG-IN ---------------------------
  { code: 'BUSWAY-100A', name: 'Busway 100A (LF)', color: '#92400E', category: 'Busway' },
  { code: 'BUSWAY-225A', name: 'Busway 225A (LF)', color: '#92400E', category: 'Busway' },
  { code: 'BUSWAY-400A', name: 'Busway 400A (LF)', color: '#92400E', category: 'Busway' },
  { code: 'BUSWAY-600A', name: 'Busway 600A (LF)', color: '#92400E', category: 'Busway' },
  { code: 'BUSWAY-PLUG-30A', name: 'Busway Plug-In 30A', color: '#92400E', category: 'Busway' },
  { code: 'BUSWAY-PLUG-60A', name: 'Busway Plug-In 60A', color: '#92400E', category: 'Busway' },
  { code: 'BUSWAY-PLUG-100A', name: 'Busway Plug-In 100A', color: '#92400E', category: 'Busway' },

  // --------------------------- MISCELLANEOUS ---------------------------
  { code: 'CORE-4', name: 'Core Drill 4"', color: '#111827', category: 'Miscellaneous' },
  { code: 'CORE-6', name: 'Core Drill 6"', color: '#111827', category: 'Miscellaneous' },
  { code: 'FIRESTOP-1', name: 'Firestopping 1"', color: '#111827', category: 'Miscellaneous' },
  { code: 'FIRESTOP-2', name: 'Firestopping 2"', color: '#111827', category: 'Miscellaneous' },
  { code: 'LABEL', name: 'Labeling/Nameplates', color: '#111827', category: 'Miscellaneous' },
  { code: 'SAW-CUT', name: 'Saw Cut Concrete', color: '#111827', category: 'Miscellaneous' },
  { code: 'PATCH', name: 'Patching/Repair', color: '#111827', category: 'Miscellaneous' },
  { code: 'MISC', name: 'Miscellaneous Item', color: '#111827', category: 'Miscellaneous' },
];